name: PluginLibrary
author: Staartvin
main: me.staartvin.plugins.pluginlibrary.PluginLibrary
version: 1.0
description: A library plugin that allows developers to easily get a lot of data from other plugins.
softdepend: [Autorank, Stats, mcMMO, Factions, afkTerminator, OnTime, RoyalCommands, UltimateCore]